# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 11:43
from __future__ import unicode_literals

from django.db import migrations

# def forwards(apps, schema_editor):
    # if not schema_editor.connection.alias == 'default':
        # return
    # pass

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
            # migrations.RunPython(forwards),
            migrations.RunSQL("CREATE FULLTEXT INDEX note_index ON main_note(note);"),
            migrations.RunSQL("CREATE FULLTEXT INDEX category_index ON " +
                "main_category(category);"),
    ]
